# listener.yml
services:

  Markocupic\ResourceBookingBundle\EventListener\ContaoHooks\Regexp:
    tags:
    - { name: contao.hook, hook: addCustomRegexp, method: onCustomRegexp, priority: 0 }

  Markocupic\ResourceBookingBundle\EventListener\ContaoHooks\ReplaceInsertTags:
    tags:
    - { name: contao.hook, hook: replaceInsertTags, method: onReplaceInsertTags, priority: 0 }
