# services.yml
services:

  # Ajax handler
  Markocupic\ResourceBookingBundle\Ajax\AjaxHandler:
    arguments:
    - '@contao.framework'
    - '@Markocupic\ResourceBookingBundle\Ajax\AjaxHelper'
    - '@session'
    - '@request_stack'
    - '@Markocupic\ResourceBookingBundle\Ajax\AjaxResponse'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    - '@security.helper'
    public: true

  # Ajax helper
  Markocupic\ResourceBookingBundle\Ajax\AjaxHelper:
    arguments:
    - '@contao.framework'
    - '@security.helper'
    - '@session'
    - '@request_stack'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    public: true

  # Json response for ajax calls
  Markocupic\ResourceBookingBundle\Ajax\AjaxResponse:
    public: true

  # Initialize application
  Markocupic\ResourceBookingBundle\AppInitialization\Initialize:
    arguments:
    - '@contao.framework'
    - '@session'
    - '@request_stack'
    - '@Markocupic\ResourceBookingBundle\Csrf\CsrfTokenManager'
    - '%resource_booking_bundle.session.attribute_bag_name%'

  # Contao frontend module "resourceBookingWeekcalendar"
  Markocupic\ResourceBookingBundle\Controller\FrontendModule\ResourceBookingWeekcalendarController:
    arguments:
    - '@contao.framework'
    - '@request_stack'
    - '@Markocupic\ResourceBookingBundle\AppInitialization\Initialize'
    - '@contao.csrf.token_storage'
    - '@Markocupic\ResourceBookingBundle\Csrf\CsrfTokenManager'
    - '@Markocupic\ResourceBookingBundle\Ajax\AjaxHandler'
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.frontend_module, category: resourceBooking, type: resourceBookingWeekcalendar }
    public: true

  # Cron: Delete daily no more used bookings
  Markocupic\ResourceBookingBundle\Cron\Cron:
    arguments:
    - '@contao.framework'
    public: true

  # CsrfTokenManager helper
  Markocupic\ResourceBookingBundle\Csrf\CsrfTokenManager:
    arguments:
    - '@request_stack'
    - '@contao.csrf.token_manager'
    - '%contao.csrf_cookie_prefix%'
    - '%contao.csrf_token_name%'
    public: true

  # Register session bag
  Markocupic\ResourceBookingBundle\Session\Attribute\ArrayAttributeBag:
    class: Markocupic\ResourceBookingBundle\Session\Attribute\ArrayAttributeBag
    arguments:
    - '@contao.framework'
    - '@request_stack'
    - '@Markocupic\ResourceBookingBundle\Csrf\CsrfTokenManager'
    - '%resource_booking_bundle.session.attribute_bag_key%'
    calls:
    - ['setName', ['%resource_booking_bundle.session.attribute_bag_name%']]



