services:
  # Register session bag
  Markocupic\ResourceBookingBundle\Session\Attribute\ArrayAttributeBag:
    arguments:
    - '%resource_booking_bundle.session.attribute_bag_key%'
    calls:
    - ['setName', ['%resource_booking_bundle.session.attribute_bag_name%']]


  # Contao frontend module "resourceBookingWeekcalendar"
  Markocupic\ResourceBookingBundle\Controller\FrontendModule\ResourceBookingWeekcalendarController:
    arguments:
    - '@security.helper'
    - '@session'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.frontend_module, category: resourceBooking, type: resourceBookingWeekcalendar }
    - { name: container.service_subscriber }
    public: true
