services:
  # Register session bag
  Markocupic\ResourceBookingBundle\Session\Attribute\ArrayAttributeBag:
    arguments:
    - '%resource_booking_bundle.session.attribute_bag_key%'
    calls:
    - ['setName', ['%resource_booking_bundle.session.attribute_bag_name%']]

  # Contao frontend module "resourceBookingWeekcalendar"
  Markocupic\ResourceBookingBundle\Controller\FrontendModule\ResourceBookingWeekcalendarController:
    arguments:
    - '@contao.framework'
    - '@security.helper'
    - '@Markocupic\ResourceBookingBundle\Session\InitializeSession'
    - '@session'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.frontend_module, category: resourceBooking, type: resourceBookingWeekcalendar }
    public: true

  # Ajax controller
  Markocupic\ResourceBookingBundle\Controller\Ajax\AjaxController:
    arguments:
    - '@contao.framework'
    - '@request_stack'
    - '@session'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    - '@Markocupic\ResourceBookingBundle\Session\InitializeSession'
    - '@Markocupic\ResourceBookingBundle\Ajax\AjaxHandler'
    public: true

  # Initialize application
  Markocupic\ResourceBookingBundle\Session\InitializeSession:
    arguments:
    - '@contao.framework'
    - '@security.helper'
    - '@session'
    - '@request_stack'
    - '%resource_booking_bundle.session.attribute_bag_name%'

  # Ajax helper
  Markocupic\ResourceBookingBundle\Ajax\AjaxHelper:
    arguments:
    - '@contao.framework'
    - '@security.helper'
    - '@session'
    - '@request_stack'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    public: true

  # Ajax handler
  Markocupic\ResourceBookingBundle\Ajax\AjaxHandler:
    arguments:
    - '@contao.framework'
    - '@Markocupic\ResourceBookingBundle\Ajax\AjaxHelper'
    - '@session'
    - '@request_stack'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    public: true

  # Cron: Delete daily no more used bookings
  Markocupic\ResourceBookingBundle\Cron\Cron:
    arguments:
    - '@contao.framework'
    public: true
