# subscriber.yml
services:
  Markocupic\ResourceBookingBundle\EventSubscriber\AjaxRequestEventSubscriber:
    arguments:
    - '@contao.framework'
    - '@Markocupic\ResourceBookingBundle\Helper\AjaxHelper'
    - '@session'
    - '@request_stack'
    - '%resource_booking_bundle.session.attribute_bag_name%'
    - '@security.helper'
    - '@event_dispatcher'
    tags:
    - { name: kernel.event_listener, event: rbb.event.fetch_data_request, method: onFetchDataRequest, priority: 10 }
    - { name: kernel.event_listener, event: rbb.event.apply_filter_request, method: onApplyFilterRequest, priority: 10 }
    - { name: kernel.event_listener, event: rbb.event.jump_week_request, method: onJumpWeekRequest, priority: 10 }
    - { name: kernel.event_listener, event: rbb.event.booking_request, method: onBookingRequest, priority: 10 }
    - { name: kernel.event_listener, event: rbb.event.booking_form_validation_request, method: onBookingFormValidationRequest, priority: 10 }
    - { name: kernel.event_listener, event: rbb.event.cancel_booking_request, method: onCancelBookingRequest, priority: 10 }
